### ISSUE TITLE
Error "crypto.getRandomValues must be defined" when creating an account

### ISSUE THREAD

**Issue by timothymcmackin** [completium/completium-cli#45] opened 2023-10-12 14:03 UTC
I'm trying to create an account in completium-cli but I get the error "crypto.getRandomValues must be defined."

I start with a fresh ubuntu container, install nodejs and npm, run `completium init`, and then run `completium-cli generate account as tim`.  Then I see the error.

There is no account named "tim" in completium, as I can see by running `completium-cli show accounts`:

```
alice                         		tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
bob                           		tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
carl                          		tz1aGDrJ58LbcnD47CkwSk3myfTxJxipYJyk
bootstrap1                    		tz1KqTpEZ7Yob7QbPE4Hy4Wo8fHG8LhKxZSx
bootstrap2                    		tz1gjaF81ZRRvdzjobyfVNsAeSC6PScjfQwN
bootstrap3                    		tz1faswCTDciRzE4oJ9jn2Vm2dvjeyA9fUzU
bootstrap4                    		tz1b7tUupMgCNw2cCLpKTkSD1NZzB5TkP2sv
bootstrap5                    		tz1ddb9NMYHZi5UzPdzTZMYQQZoMub195zgv
```

How can I get this working?

**Comment by timothymcmackin** [comment] 2023-10-12 14:50
@guillaumeduhamel There is no stack trace; all I see is the error. Is there some --verbose option to get the trace?
<img width="383" alt="Screenshot 2023-10-12 at 10 49 49 AM" src="https://github.com/completium/completium-cli/assets/6494785/5d498f0c-8bb8-4d74-a1a6-9ed9a16e18c0">

**Comment by guillaumeduhamel** [comment] 2023-10-12 15:16
erf, ok, thanks.
Unfortunately, the error seems to be triggered by dependencies.
Could you please provide details about your environment?
I will try to reproduce the error.

**Comment by timothymcmackin** [comment] 2023-10-12 15:24
I'm using a Docker ubuntu image, currently the latest: 6a47e077731f

1. Start the image by running `docker run -it --entrypoint /bin/sh --name ubuntu-completium ubuntu`
2. Install Node and NPM by running `apt update; apt install -y nodejs npm`
3. Install completium by running `npm install -g @completium/completium-cli`
4. Init completium by running `completium-cli init`
5. Generate an account by running `completium-cli generate account as tim`
Then I see the error.

I get similar results on zsh in macos Sonoma.

**Comment by guillaumeduhamel** [comment] 2023-10-12 16:58
Got it !
A new version of `completium-cli` has been released.
If you follow the instructions again, it should work correctly.
Please let me know if it works on your end,

**Comment by timothymcmackin** [comment] 2023-10-12 17:05
That works. Thanks for the quick fix!

**Comment by guillaumeduhamel** [comment] 2023-10-12 17:25
Great ! Thank you for the report, I close the issue

**Closed by guillaumeduhamel** 2023-10-12 17:25 UTC
